name: calc_steps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  kumi_popup_window: ^2.0.1
  shared_preferences: ^2.2.2
  window_size:
    git:
     url: https://github.com/google/flutter-desktop-embedding
     path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - image/